{% set name = "pyrte_rrtmgp" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/earth-system-radiation/pyRTE-RRTMGP/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b53de2a06648f3bdd719dfea07d31fec7f266519a4de5a2028535c4ecf8f9808

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake ==3.26.4
    - make

  host:
    - netcdf4 >=1.5.7
    - numpy
    - pip
    - pybind11 >=2.10.0
    - python >=3.11,<3.13
    - rte_rrtmgp ==v1.9.1
    - scikit-build-core
    - urllib3
    - xarray >=2023.5.0

  run:
    - netcdf4 >=1.5.7
    - numpy >=1.21.0
    - python >=3.11,<3.13
    - rte_rrtmgp ==v1.9.1
    - urllib3
    - xarray >=2023.5.0

test:
  imports:
    - pyrte_rrtmgp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/earth-system-radiation/pyRTE-RRTMGP
  summary: A Python interface to the RTE+RRTMGP Fortran software package.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://pyrte-rrtmgp.readthedocs.io/

extra:
  recipe-maintainers:
    - giancastro
    - RobertPincus
